version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: always
    ports:
      - "${PORT_FRONTEND}:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
